#pragma once
#define _CRT_SECURE_NO_WARNINGS
#define HELP_CONSOLE_OPTION_1 "-h"
#define HELP_CONSOLE_OPTION_2 "--help"
#define GENKEY_CONSOLE_OPTION "genkey"
#define SIGNATURE_CONSOLE_OPTION "sign"
#define CHECK_CONSOLE_OPTION "check"
#define ENCRYPT_CONSOLE_OPTION "encrypt"
#define DECRYPT_CONSOLE_OPTION "decrypt"
#define SIZE_CONSOLE_OPTION "--size"
#define PUBKEY_CONSOLE_OPTION "--pubkey"
#define SECRET_CONSOLE_OPTION "--secret"
#define SIGFILE_CONSOLE_OPTION "--sigfile"
#define INFILE_CONSOLE_OPTION "--infile"
#define OUTFILE_CONSOLE_OPTION "--outfile"
